src/Web/Controllers/StoreController.cs
using System.Linq;
using System.Web.Mvc;
using Depot.Web.Filters;
using Depot.Web.Helpers;
using Depot.Web.Models;
using Raven.Client;
using Raven.Client.Linq;
using Depot.Web.Extensions;

namespace Depot.Web.Controllers
{
    [RavenDocumentSession]
    public class StoreController: AutoMapperController
    {
        private readonly IDocumentSession _session;

        public StoreController(IDocumentSession session)
        {
            _session = session;
        }

        public ActionResult Index()
        {
            var products = _session.Query<Product>().OrderBy(product => product.Title).ToArray();
            return AutoMapView<ProductListModel[]>(products, View());
        }

        private Cart FindCart()
        {
            if (Session["Cart"] == null)
                Session["Cart"] = new Cart();
            return Session["Cart"] as Cart;
        }

        [HttpPost]
        public ActionResult AddToCart(int id)
        {
            var product = _session.Load<Product>(id);
            if (product == null)
                return RedirectToAction("Index").WithFlash(FlashMessageType.Error, "Product was not found");
            var cart = FindCart();
            cart.AddProduct(product);
            return View(cart);
        }

        [HttpPost]
        public ActionResult EmptyCart()
        {
            Session["Cart"] = null;
            return RedirectToAction("Index").WithFlash(FlashMessageType.Notice, "Your cart is currently empty");
        }
    }

    
}

src/Web/Views/Store/AddToCart.cshtml
@model Depot.Web.Models.Cart

@{
    Layout = "~/Views/Shared/Store.cshtml";
}

<div class="cart-title">Your Cart</div>
<table>
    @foreach (var item in Model.Items)
    {
        <tr>
            <td>@item.Quantity &times;</td>
            <td>@item.Title</td>
            <td class="item-price">$@item.Price</td>
        </tr>
    }
    
    <tr class="total-line">
        <td colspan="2">Total</td>
        <td class="total-cell">$@Model.TotalPrice</td>
    </tr>
</table>

@using(Html.BeginForm("EmptyCart", "Store"))
{
    <input type="submit" value="Empty cart"/>
}

src/Web/Views/Store/Index.cshtml
@model Depot.Web.Models.ProductListModel[]

@{
    ViewBag.Title = "Your Pragmatic Catalog";
    Layout = "~/Views/Shared/Store.cshtml";
}

<h1>Your Pragmatic Catalog</h1>
@foreach(var product in Model)
{
    <div class="entry">
        <img src="@product.ImageUrl" alt="@product.Title"/>
        <h3>@product.Title</h3>
        @Html.Raw(@product.Description)
        <div class="price-line">
            <span class="price">@Html.DisplayFor(modelItem => product.Price)</span>
            @using (Html.BeginForm("AddToCart", "Store", new {id = product.Id}))
            {
                <input type="submit" value="Add to Cart"/>
            }
        </div>
    </div>
}